services:
  database:
    image: postgis/postgis:16-3.4
    container_name: shops_db
    hostname: shops_db
    networks: 
      - mynet
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbshops

volumes:
  pgdata:

networks:
  mynet:
    driver: bridge
